baseURL = "https://example.com"
title = "Kalpataru AI"
author = "Harsha S"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo.png"
    alt = "Kalpataru AI"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Kalpataru AI"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Kalpataru AI is a company that provides innovative technology solutions to businesses and individuals seeking innovative strategy and technology."
    meta_og_title = "Kalpataru AI"
    meta_og_type = "website"
    meta_og_url = "https://kalpataru.ai"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Kalpataru AI is a company that provides innovative technology solutions to businesses and individuals seeking innovative strategy and technology."
    meta_twitter_card = "Kalpataru AI"
    meta_twitter_site = "@KalpataruAI"
    meta_twitter_creator = "@KalpataruAI"

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Products"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/KalpataruAI"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2